[package]
name = "huffman-ft-uyen"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
env_logger = "0.11.6"
get-size = "=0.1.4"
log = "0.4.25"
serde = { version = "1.0", features = ["derive"] }
structopt = "0.3.26"
